language: node_js
dist: trusty
sudo: required
node_js:
  - "10"
  - "12"

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

addons:
  chrome: stable

script:
  - npm test
  - npm run codecov

notifications:
  email: false
